[package]
name = "SimplePipeSim"
version = "0.1.0"
edition = "2021"

[dependencies]
object = "0.36.7" # for ELF format parsing
clap = "4.5.35" # command line argument parser
rand = "0.9.1" # random number genertion
log = "0.4.27" # framework for logging
colog = "1.3.0"
cc = "1.2.22"
libc = "0.2.172"

[features]
show_log = []
